### ISSUE TITLE
defaultValue prevents visibleExpression to work when in edit-mode of form

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-expressions#9]
### How to Reproduce
Attribute X has three options and Attribute X has defaultValue 3.
Atrribute Y is only visible when option 3 is selected. 
Open new form including attributes X and Y.

### Expected behavior
When opening new form Attribute X and Atrribute Y are visible.

### Observed behavior
When opening new form ONLY Attribute X is visible. Possible workaround is also not working. When changing option in Attribute X and returning to option 3 does not make Atrribute Y visible.

Attached: EMX from cranio, example can be
[cranio_9_0.xlsx](https://github.com/molgenis/molgenis-expressions/files/6975185/cranio_9_0.xlsx)
found in "cranio_NL1_subject" with AttributeX: "agediagnosis" and Attribute Y: "agediagnosisdate"

**Comment by MaxPostema** [comment]
Not an issue, For any one that finds the same problem. 

Note that when using a mref field the check is on an array of values.
```
{my_singlevalue} = '3'
{my_mref} contains '3'
```
